### ISSUE TITLE
'required' does not exist in type 'ScalarArgConfig<string>'

### ISSUE THREAD

**Issue by ashih42** [graphql-nexus/schema#679]
Hello,

I have the following code that was working in `@nexus/schema` 0.18.0 before.
```
import { mutationField, stringArg } from "@nexus/schema";

export const do_something = mutationField("do_something", {
  type: "String",
  args: {
    name: stringArg({ required: true }),
  },
  resolve: async (root, args, context) => {
    const { name } = args;
    return name;
  },
});
```

After upgrading `@nexus/schema` to 0.19.0 or 0.19.1, I get the following error with `ts-node` 9.0.0 :
```
/home/ash/nexus_test/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/GraphqlServer/Types/Mutation/index.ts:6:23 - error TS2345: Argument of type '{ required: boolean; }' is not assignable to parameter of type 'ScalarArgConfig<string>'.
  Object literal may only specify known properties, and 'required' does not exist in type 'ScalarArgConfig<string>'.

6     name: stringArg({ required: true }),
```

Could anyone explain what might be the issue?  Did some syntax change in the newest version making the code invalid?

Thank you for your time and consideration.

**Comment by ashih42** [comment]
I see, those options are gone and replaced with these functions.
https://nexusjs.org/docs/api/list-nonNull

**Comment by tgriesser** [comment]
These should be available again if you install the `declarativeWrappingPlugin`.
