### ISSUE TITLE
ts-node-dev no longer works when upgrading from 0.16.0 to 0.17.0

### ISSUE THREAD

**Issue by tiago-loureiro** [graphql-nexus/schema#645]
Hello, I am using `ts-node-dev ver. 1.0.0 (using ts-node ver. 9.0.0, typescript ver. 4.1.2)` and getting the following error when running:

`yarn ts-node-dev --transpile-only --no-notify src/backend/index.ts`

```
TypeError: type.getInterfaces is not a function
    at /backend/node_modules/@nexus/schema/src/builder.ts:1056:31
    at Array.forEach (<anonymous>)
    at SchemaBuilder.buildInterfaceList (/backend/node_modules/@nexus/schema/src/builder.ts:1054:16)
    at interfaces (/backend/node_modules/@nexus/schema/src/builder.ts:869:30)
    at resolveThunk (/backend/node_modules/graphql/type/definition.js:438:40)
    at defineInterfaces (/backend/node_modules/graphql/type/definition.js:619:20)
    at GraphQLObjectType.getInterfaces (/backend/node_modules/graphql/type/definition.js:587:31)
    at typeMapReducer (/backend/node_modules/graphql/type/schema.js:276:28)
    at typeMapReducer (/backend/node_modules/graphql/type/schema.js:286:20)
    at typeMapReducer (/backend/node_modules/graphql/type/schema.js:286:20)
```

and my `package.json` looks like this:

```
  "dependencies": {
    "@graphile-contrib/pg-order-by-related": "^1.0.0-beta.6",
    "@graphile-contrib/pg-simplify-inflector": "^6.1.0",
    "@graphql-codegen/cli": "1.19.2",
    "@graphql-codegen/typescript": "1.17.11",
    "@graphql-codegen/typescript-generic-sdk": "^1.17.8",
    "@graphql-mesh/cli": "^0.11.12",
    "@graphql-mesh/postgraphile": "^0.7.10",
    "@nexus/schema": "^0.17.0",
    "@types/node": "^14.14.9",
    "@types/uuid": "^8.3.0",
    "apollo-server": "^2.19.0",
    "apollo-server-express": "^2.19.0",
    "dotenv": "^8.2.0",
    "firebase-admin": "^9.4.1",
    "get-port": "^5.1.1",
    "graphql-middleware": "^4.0.2",
    "graphql-relay": "^0.6.0",
    "graphql-shield": "^7.4.1",
    "ip": "^1.1.5",
    "node-mocks-http": "^1.9.0",
    "postgraphile-plugin-connection-filter": "^2.1.1",
    "postgraphile-plugin-nested-mutations": "^1.0.1",
    "postgres-migrations": "^5.1.0",
    "uuid": "^8.3.1",
    "validator": "^13.1.17"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true,
    "trailingComma": "all"
  },
  "devDependencies": {
    "@types/graphql-relay": "^0.6.0",
    "@types/ip": "^1.1.0",
    "@types/jest": "^26.0.15",
    "@types/validator": "^13.1.0",
    "@typescript-eslint/eslint-plugin": "^4.8.1",
    "@typescript-eslint/parser": "^4.8.1",
    "aws-sdk": "^2.796.0",
    "concurrently": "^5.3.0",
    "eslint": "^7.12.1",
    "firebase": "^8.1.1",
    "graphql-request": "^3.3.0",
    "jest": "^26.6.2",
    "prettier": "2.2.0",
    "ts-jest": "^26.4.3",
    "ts-node-dev": "^1.0.0",
    "typescript": "^4.1.2"
  }
```

This worked fine with `nexus-schema` version `0.16.0`, issue appeared when trying to upgrade to `0.17.0`

**Comment by ikusa** [comment]
Also having this issue after upgrading from 0.17.0. I think because of interface new spec getting implemented in #496 .

![image](https://user-images.githubusercontent.com/18739325/100003575-e316e580-2df8-11eb-8b95-2730904a5d5d.png)

**Comment by tgriesser** [comment]
Adding the latest `graphql` in your dependencies should fix this. Nexus now has a peer dependency on graphql `15.x`, which added interfaces being able to implement interfaces.
